/**
 * Created by Mave on 2015/4/3 0003.
 * Page 89 Question 1: Calculate average score of the whole 30 students, score should be generated by Math.random() and its value should around 0 to 100.
 */
public class Ex21_CalculateAverage {
    public static void main(String[] args) {
        double sum = 0.0;
        int[] score = new int[30];
        double tempScore;
        int trimmedTempScore;
        for (int i = 1; i <= 30; i++) {
            tempScore = Math.random() * 100;        //Generate score using Math.random()
            trimmedTempScore = (int) (Math.round(tempScore));     //Trim score
            score[i - 1] = trimmedTempScore;
            sum += trimmedTempScore;

            System.out.println("Generated student #" + i + "'s score: " + trimmedTempScore + " <-- " + tempScore);
        }
        System.out.println("------");
        System.out.println("Sum is: " + sum);
        System.out.println("Average is: " + sum / 30.0);
    }
}
